SOPRANO_PART_NUMBER = 0
ALTO_PART_NUMBER = 1
TENOR_PART_NUMBER = 2
BASS_PART_NUMBER = 3

PART_NAMES = {
    SOPRANO_PART_NUMBER: "soprano",
    ALTO_PART_NUMBER: "alto",
    TENOR_PART_NUMBER: "tenor",
    BASS_PART_NUMBER: "bass"
}
